#!/bin/zsh
#=== HELPER METHODS ===================================
function error() { print -P "%F{160}[ERROR] ---%f%b $1" >&2 && exit 1; }
function info() { print -P "%F{34}[INFO] ---%f%b $1"; }
#=== ZINIT ============================================
# GIT_REPO=$(git rev-parse --show-toplevel)/tests/_support/zinit
GIT_REPO=$(mktemp -d)/zinit
if [[ -d $GIT_REPO ]]; then
  rm -rf $GIT_REPO
fi
typeset -gAH ZINIT;
ZINIT[HOME_DIR]=$GIT_REPO  ZPFX=$ZINIT[HOME_DIR]/polaris
ZINIT[BIN_DIR]=$ZINIT[HOME_DIR]/zinit.git ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
ZINIT[COMPLETIONS_DIR]=$ZINIT[HOME_DIR]/completions ZINIT[SNIPPETS_DIR]=$ZINIT[HOME_DIR]/snippets
ZINIT[ZCOMPDUMP_PATH]=$ZINIT[HOME_DIR]/zcompdump    ZINIT[PLUGINS_DIR]=$ZINIT[HOME_DIR]/plugins
ZI_REPO='zdharma-continuum'; GH_RAW_URL='https://raw.githubusercontent.com'
info 'Downloading Zinit' \
  && command git clone \
      --branch 'fix/gh-r-logic' \
      https://github.com/vladdoster/zinit \
      $ZINIT[BIN_DIR] \
  || error 'Unable to download zinit' \
  && info 'Installing Zinit' \
  && command chmod g-rwX $ZINIT[HOME_DIR] \
  && zcompile $ZINIT[BIN_DIR]/zinit.zsh \
  && info 'Successfully installed Zinit' \
  || error 'Unable to install Zinit'
source $ZINIT[BIN_DIR]/zinit.zsh \
  && autoload -Uz _zinit \
  && (( ${+_comps} )) \
  && _comps[zinit]=_zinit

zi for \
    as"null" \
    atclone"./install -e no -d ${HOME}/.local" \
    atinit"export PATH=${HOME}/.local/bin:${PATH}" \
    atpull"%atclone" \
    depth"1" lucid nocompile nocompletions \
  @romkatv/zsh-bin \
    light-mode \
  zdharma-continuum/zinit-annex-{'bin-gem-node','default-ice','binary-symlink'}

zi as'program' for \
    pick"revolver" \
    mv'revolver.zsh-completion -> _revolver' \
  molovo/revolver \
    atclone'./build.zsh' \
    mv'zunit.zsh-completion -> _zunit' \
    pick"zunit" \
  zunit-zsh/zunit
