#!/usr/bin/env zsh

# Log functions [[[
function error() { print -P "%F{160}[ERROR] ---%f%b $1" >&2 && exit 1; }
function info() { print -P "%F{34}[INFO] ---%f%b $1"; }
# ]]]

# Install Zinit [[[
GIT_REPO=$(mktemp -d)/zinit
typeset -gAH ZINIT;
ZINIT[HOME_DIR]=$GIT_REPO  ZPFX=$ZINIT[HOME_DIR]/polaris
ZINIT[BIN_DIR]=$ZINIT[HOME_DIR]/zinit.git ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
ZINIT[COMPLETIONS_DIR]=$ZINIT[HOME_DIR]/completions ZINIT[SNIPPETS_DIR]=$ZINIT[HOME_DIR]/snippets
ZINIT[ZCOMPDUMP_PATH]=$ZINIT[HOME_DIR]/zcompdump    ZINIT[PLUGINS_DIR]=$ZINIT[HOME_DIR]/plugins
ZI_REPO='zdharma-continuum'; GH_RAW_URL='https://raw.githubusercontent.com'
info 'Downloading Zinit' \
  && command git clone \
      --branch 'refactor/zunit-tests' \
      https://github.com/$ZI_REPO/zinit.git \
      $ZINIT[BIN_DIR] \
  || error 'Unable to download zinit' \
  && info 'Installing Zinit' \
  && command chmod g-rwX $ZINIT[HOME_DIR] \
  && zcompile $ZINIT[BIN_DIR]/zinit.zsh \
  && info 'Successfully installed Zinit' \
  || error 'Unable to install Zinit'
source $ZINIT[BIN_DIR]/zinit.zsh \
  && autoload -Uz _zinit \
  && (( ${+_comps} )) \
  && _comps[zinit]=_zinit
# ]]]
#
# Install Annexes [[[
zinit light-mode for $ZI_REPO/zinit-annex-{'bin-gem-node','binary-symlink','default-ice','patch-dl'}
# vim:ft=zsh:sw=4:sts=4:et:foldmarker=[[[,]]]:foldmethod=marker
