name: Unit tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TERM: xterm

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: "install dependencies"
        run: brew install svn unzip zsh

      - name: "install zunit"
        run: brew install vladdoster/zunit/zunit

      - name: "${{ matrix.os }}"
        run: zunit
