name: Unit tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TERM: xterm

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: "install dependencies"
        run: |
          brew install svn unzip zsh

      - name: "install zunit"
        run: brew install vladdoster/zunit/zunit

      - name: "${{ matrix.os }}"
        run: |
          zunit --fail-fast --time-limit 60 --verbose
